### ISSUE TITLE
'apache2-foreground' not found or does not exist

### ISSUE THREAD

**Issue by wuestkamp** [jakubsacha/symfony-docker#2]
Hi,

I'm on Ubuntu 14.04 and docker version 1.11.1, when trying to run this container I get:

`docker: Error response from daemon: Container command 'apache2-foreground' not found or does not exist..`

Any idea if that's docker or this container?

Thanks,
Kim

**Comment by jakubsacha** [comment]
Interesting. Could you give me some details how do you invoke it, please?

**Comment by wuestkamp** [comment]
Sure, I call it like this:

`sudo docker run -t -i -p 8080:80 -v /home/user/project:/var/www/ "jakubsacha/symfony-docker:php7-dev"`

**Comment by wuestkamp** [comment]
Its now working if I call it like this:

`sudo docker run -t -i -p 8080:80 -v /home/user/project:/var/www/html "jakubsacha/symfony-docker:php7-dev"`

So I changed the mapping from `/var/www` to `/var/www/html`
