### ISSUE TITLE
php7-dev xdebug.so location has changed?

### ISSUE THREAD

**Issue by AaronSoap** [jakubsacha/symfony-docker#3]
Hey,

Just using this container and noticed xdebug has disappeared.

Had a look and I think the location of the xdebug so has changed.

In the docker file it adds the line:

"zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20151012/xdebug.so"

taking a look in the container after a build:

```
root@fc1652c0f74d:/var/www/html# find / -name 'xdebug.so'
/usr/local/lib/php/extensions/no-debug-non-zts-20160303/xdebug.so
```

I guess it just needs changing?

I would do it but im clueless as to how you test a docker container.

**Comment by jakubsacha** [comment]
Hey @AaronSoap, thanks for your report. It should be fixed on master now. Try to pull newer version of the image.

I've added also support for php 7.1.
